import { UserRole } from '../enums.js';
import { PERMISSIONS, type PermissionKey } from './permissions.js';

export const ROLE_LABELS: Record<UserRole, string> = {
  [UserRole.SUPER_ADMIN]: 'Super Admin',
  [UserRole.ADMIN]: 'Admin',
  [UserRole.PRODUCT_MANAGER]: 'Product Manager',
  [UserRole.ENGINEER]: 'Engineer',
  [UserRole.CLIENT]: 'Client',
  [UserRole.TESTING]: 'Testing',
};

export const ROLE_HIERARCHY: UserRole[] = [
  UserRole.SUPER_ADMIN,
  UserRole.ADMIN,
  UserRole.PRODUCT_MANAGER,
  UserRole.ENGINEER,
  UserRole.CLIENT,
  UserRole.TESTING,
];

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  [UserRole.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [UserRole.TESTING]: Object.values(PERMISSIONS),

  [UserRole.ADMIN]: [
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.PROJECT_VIEW_ALL,
    PERMISSIONS.PROJECT_VIEW_ASSIGNED,
    PERMISSIONS.PROJECT_SET_HEALTH,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT_ANY,
    PERMISSIONS.TASK_EDIT_OWN,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_MOVE_STATUS,
    PERMISSIONS.TASK_REQUEST_REVIEW,
    PERMISSIONS.TASK_TRANSITION_DONE,
    PERMISSIONS.TASK_VIEW_INTERNAL,
    PERMISSIONS.TASK_MARK_BLOCKED,
    PERMISSIONS.MILESTONE_CREATE,
    PERMISSIONS.MILESTONE_EDIT,
    PERMISSIONS.MILESTONE_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_EDIT,
    PERMISSIONS.USER_DEACTIVATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_PORTFOLIO,
    PERMISSIONS.ANALYTICS_VIEW_PROJECT,
    PERMISSIONS.ANALYTICS_VIEW_TEAM,
    PERMISSIONS.DECISION_CREATE,
    PERMISSIONS.DECISION_EDIT,
    PERMISSIONS.DECISION_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW,
    PERMISSIONS.DELIVERABLE_CREATE,
    PERMISSIONS.DELIVERABLE_EDIT,
    PERMISSIONS.DELIVERABLE_DELETE,
    PERMISSIONS.INTEGRATION_MANAGE,
    // Project Documents
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
    // Products (PR C)
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_DELETE,
  ],

  [UserRole.PRODUCT_MANAGER]: [
    PERMISSIONS.PROJECT_EDIT,
    PERMISSIONS.PROJECT_VIEW_ASSIGNED,
    PERMISSIONS.PROJECT_SET_HEALTH,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT_ANY,
    PERMISSIONS.TASK_EDIT_OWN,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_MOVE_STATUS,
    PERMISSIONS.TASK_REQUEST_REVIEW,
    PERMISSIONS.TASK_TRANSITION_DONE,
    PERMISSIONS.TASK_VIEW_INTERNAL,
    PERMISSIONS.TASK_MARK_BLOCKED,
    PERMISSIONS.MILESTONE_CREATE,
    PERMISSIONS.MILESTONE_EDIT,
    PERMISSIONS.MILESTONE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_PROJECT,
    PERMISSIONS.ANALYTICS_VIEW_TEAM,
    PERMISSIONS.DECISION_CREATE,
    PERMISSIONS.DECISION_EDIT,
    PERMISSIONS.DECISION_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW,
    PERMISSIONS.DELIVERABLE_CREATE,
    PERMISSIONS.DELIVERABLE_EDIT,
    PERMISSIONS.DELIVERABLE_DELETE,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.PRODUCT_VIEW,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_EDIT,
    PERMISSIONS.PRODUCT_DELETE,
  ],

  [UserRole.ENGINEER]: [
    PERMISSIONS.PROJECT_VIEW_ASSIGNED,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_EDIT_OWN,
    PERMISSIONS.TASK_MOVE_STATUS,
    PERMISSIONS.TASK_REQUEST_REVIEW,
    PERMISSIONS.TASK_TRANSITION_DONE,
    PERMISSIONS.TASK_VIEW_INTERNAL,
    PERMISSIONS.TASK_MARK_BLOCKED,
    PERMISSIONS.MILESTONE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_PROJECT,
    PERMISSIONS.DECISION_CREATE,
    PERMISSIONS.DECISION_VIEW,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW,
    PERMISSIONS.DELIVERABLE_EDIT,
    // Engineers can upload, read, and delete documents on projects they're on.
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
    // Engineers read the product taxonomy but don't reshape it; product
    // strategy lives with admin/PM.
    PERMISSIONS.PRODUCT_VIEW,
  ],

  [UserRole.CLIENT]: [
    PERMISSIONS.PROJECT_VIEW_ASSIGNED,
    PERMISSIONS.TASK_VIEW_CLIENT_VISIBLE,
    // Clients can submit task REQUESTS from their portal kanban. The
    // service layer forces clientVisible=true, status=BACKLOG, and
    // clientRequested=true on every row this permission creates — the
    // team triages from there. This is narrower than TASK_CREATE; it
    // doesn't unlock assigneeId, sprintId, priority overrides, etc.
    PERMISSIONS.TASK_CREATE_REQUEST,
    PERMISSIONS.MILESTONE_VIEW,
    PERMISSIONS.ANALYTICS_VIEW_PROJECT,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_VIEW,
    PERMISSIONS.DELIVERABLE_SIGN_OFF,
    // Clients can browse + download docs the team has shared, but
    // cannot upload or delete. The team curates what's visible.
    PERMISSIONS.DOCUMENT_READ,
    // Clients read the product taxonomy so they can scope their work
    // requests + bug submissions to the right product. They can't
    // create/edit/delete — the team owns naming.
    PERMISSIONS.PRODUCT_VIEW,
  ],
};

// NOTE (2026-06-02): the old `EXTENDED_CLIENT_ADDITIONAL_PERMISSIONS` global
// CLIENT grant was retired in favour of the per-project
// `ProjectMember.fullAccess` model (see backend
// `rbac.service.canViewProjectInternal`). Giving a client the full internal
// view of a project is now a per-project, SUPER_ADMIN-only grant — there is
// no longer a global per-user permission union.
