/**
 * Build the Exargen Command Center product guide as a Word document.
 *
 * Produces docs/PRODUCT_GUIDE.docx — a self-contained reference with:
 *   - Cover page
 *   - Table of contents (auto-generated by Word)
 *   - 13 chapters covering every feature
 *   - All 9 screenshots embedded under their feature, with figure numbers
 *   - Page numbers in the footer, doc title in the header
 *
 * Run from repo root:
 *   npx tsx scripts/build-product-guide-docx.ts
 */
import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, ImageRun,
  Header, Footer, AlignmentType, PageOrientation, LevelFormat,
  TabStopType, TabStopPosition, BorderStyle, WidthType, ShadingType,
  HeadingLevel, PageNumber, PageBreak, TableOfContents, VerticalAlign,
} from 'docx';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const SCREENSHOTS = path.join(ROOT, 'docs/screenshots');
const OUTPUT = path.join(ROOT, 'docs/PRODUCT_GUIDE.docx');

// ─── Style + helper functions ─────────────────────────────────────────────────

const FONT = 'Arial';
const TITLE_COLOR = '1F1F1F';
const SUBTLE_COLOR = '6B6B6B';
const ACCENT_COLOR = '7C3AED'; // Brand violet

function p(text: string, opts: { italic?: boolean; bold?: boolean; size?: number } = {}): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({
      text,
      font: FONT,
      italics: opts.italic,
      bold: opts.bold,
      size: opts.size ?? 22, // 11pt default
    })],
  });
}

function pmix(...runs: TextRun[]): Paragraph {
  return new Paragraph({ spacing: { after: 120 }, children: runs });
}

function h1(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    pageBreakBefore: true,
    children: [new TextRun({ text, font: FONT, bold: true, size: 36, color: TITLE_COLOR })],
  });
}

function h2(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, font: FONT, bold: true, size: 28, color: TITLE_COLOR })],
  });
}

function h3(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    children: [new TextRun({ text, font: FONT, bold: true, size: 24, color: TITLE_COLOR })],
  });
}

function bullets(items: string[]): Paragraph[] {
  return items.map((text) => new Paragraph({
    numbering: { reference: 'bullets', level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, font: FONT, size: 22 })],
  }));
}

function numbered(items: string[]): Paragraph[] {
  return items.map((text) => new Paragraph({
    numbering: { reference: 'numbers', level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, font: FONT, size: 22 })],
  }));
}

function quote(text: string, by?: string): Paragraph[] {
  return [
    new Paragraph({
      indent: { left: 720 },
      spacing: { after: 60 },
      border: { left: { style: BorderStyle.SINGLE, size: 24, color: ACCENT_COLOR, space: 12 } },
      children: [new TextRun({ text, font: FONT, italics: true, size: 22, color: SUBTLE_COLOR })],
    }),
    ...(by
      ? [new Paragraph({
          indent: { left: 720 },
          spacing: { after: 200 },
          children: [new TextRun({ text: `— ${by}`, font: FONT, italics: true, size: 20, color: SUBTLE_COLOR })],
        })]
      : []),
  ];
}

let figureCounter = 0;
function figure(filename: string, caption: string, opts: { width?: number; height?: number } = {}): Paragraph[] {
  figureCounter += 1;
  const data = fs.readFileSync(path.join(SCREENSHOTS, filename));
  // 9360 DXA content width = 6.5". docx-js images use pixels, so use 600x375 (8:5)
  // for landscape captures while staying inside the page width.
  const width = opts.width ?? 600;
  const height = opts.height ?? 375;
  return [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 80 },
      children: [new ImageRun({
        type: 'png',
        data,
        transformation: { width, height },
        altText: { title: caption, description: caption, name: filename },
      })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [
        new TextRun({ text: `Figure ${figureCounter}. `, font: FONT, bold: true, italics: true, size: 18, color: SUBTLE_COLOR }),
        new TextRun({ text: caption, font: FONT, italics: true, size: 18, color: SUBTLE_COLOR }),
      ],
    }),
  ];
}

const cellMargin = { top: 80, bottom: 80, left: 120, right: 120 };
const cellBorder = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' };
const cellBorders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder };

function table(headers: string[], rows: string[][]): Table {
  // Total table width: 9360 DXA (US Letter content width with 1" margins)
  const colCount = headers.length;
  const totalWidth = 9360;
  const colWidth = Math.floor(totalWidth / colCount);
  const columnWidths = headers.map(() => colWidth);
  // Adjust the last column to absorb rounding so widths sum exactly.
  columnWidths[colCount - 1] = totalWidth - colWidth * (colCount - 1);

  return new Table({
    width: { size: totalWidth, type: WidthType.DXA },
    columnWidths,
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map((h, i) => new TableCell({
          borders: cellBorders,
          width: { size: columnWidths[i], type: WidthType.DXA },
          shading: { fill: 'EAE6F8', type: ShadingType.CLEAR },
          margins: cellMargin,
          children: [new Paragraph({ children: [new TextRun({ text: h, font: FONT, bold: true, size: 20 })] })],
        })),
      }),
      ...rows.map((row) => new TableRow({
        children: row.map((cell, i) => new TableCell({
          borders: cellBorders,
          width: { size: columnWidths[i], type: WidthType.DXA },
          margins: cellMargin,
          children: cell.split('\n').map((line) => new Paragraph({
            children: [new TextRun({ text: line, font: FONT, size: 20 })],
          })),
        })),
      })),
    ],
  });
}

// Spacer paragraph used between elements to keep sections breathable.
const spacer = () => new Paragraph({ spacing: { after: 100 }, children: [new TextRun('')] });

// ─── Cover page ───────────────────────────────────────────────────────────────

const coverPage: Paragraph[] = [
  new Paragraph({ spacing: { before: 2400 }, children: [new TextRun('')] }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 240 },
    children: [new TextRun({ text: 'EXARGEN', font: FONT, bold: true, size: 48, color: ACCENT_COLOR })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 480 },
    children: [new TextRun({ text: 'Command Center', font: FONT, size: 56, color: TITLE_COLOR })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 720 },
    children: [new TextRun({
      text: 'The complete product guide',
      font: FONT, italics: true, size: 28, color: SUBTLE_COLOR,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 240 },
    children: [new TextRun({
      text: 'A multi-product project-management platform for the Exargen studio.',
      font: FONT, size: 22, color: TITLE_COLOR,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 1800 },
    children: [new TextRun({
      text: '8 products. 1 cockpit. Built for serious work.',
      font: FONT, size: 22, color: SUBTLE_COLOR,
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: `Version ${new Date().toISOString().slice(0, 10)}`, font: FONT, size: 18, color: SUBTLE_COLOR })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'Internal — Single Source of Truth', font: FONT, italics: true, size: 18, color: SUBTLE_COLOR })],
  }),
];

// ─── Body content ─────────────────────────────────────────────────────────────

const body: (Paragraph | Table)[] = [];

// === Chapter 1: Welcome ===
body.push(h1('Welcome to the Command Center'));
body.push(p(
  "Imagine you are running a small workshop that builds eight different things at once — a robot, a calendar, a phone app, a car-sharing service, a security tool, a shop till, an analytics dashboard, and a tiny game. Each one has its own team, its own to-do list, its own deadlines. How do you keep track of them all without losing your mind?",
));
body.push(p(
  "The Exargen Command Center is the answer. It is one website where everyone — the founder, the product managers, the engineers, even the customers — can sign in and see exactly what they need to see. No more flipping between ten different apps. No more 'where did I write that down?' moments.",
));
body.push(h2('Think of it like a building'));
body.push(p('Every part of the platform has a real-world cousin. Once you see them, the whole thing makes sense.'));
body.push(...bullets([
  "The front door is the Studio Portfolio — when admins walk in, they see a giant board showing how all eight products are doing.",
  "The doormat is the Triage Inbox — a small pile of decisions that came in overnight. Clear it before you do anything else.",
  "Each product gets its own room (called a Project). Inside the room are different tabs: a wall of sticky notes (the Board), a calendar of two-week chunks of work (Sprints), a list of big themes (Epics), and a settings drawer.",
  "Every sticky note is a Task — one piece of work, with everything you need to know about it: who's doing it, what counts as 'done', what other tasks it depends on.",
]));
body.push(h2('Why we built our own'));
body.push(p(
  "There are tools out there that do bits of this — Linear is fast, Jira is powerful, Notion is flexible, Trello is simple. But none of them are designed for a studio that runs eight separate products at the same time. They make you log in to a different workspace per product, or they bury the cross-product view three clicks deep.",
));
body.push(p(
  "Our platform takes the best ideas from all those tools and stitches them together. Linear's keyboard speed. Jira's structured fields. Height's hover-preview triage. Notion's flexible layout. Stitched into one cohesive product, designed first for the studio altitude (all eight products at once) and second for the project altitude (one product up close).",
));

// === Chapter 2: Who uses it ===
body.push(h1('Who Uses This Platform'));
body.push(p(
  "Different people sign in and see different things. The platform automatically adjusts based on your role — you don't need to fiddle with settings.",
));
body.push(table(
  ['Role', 'Who they are', 'What they see when they log in'],
  [
    ['Super Admin / Admin', 'The founder. Senior leadership.', "The whole studio. The Studio Portfolio (homepage), the Triage Inbox, every project, every user, all settings."],
    ['Product Manager (PM)', "The person responsible for one or more products.", "Their projects' Board, Sprints, Epics, Timeline, Decisions, Settings."],
    ['Engineer', 'Software engineers, designers, anyone building.', "Their personal dashboard with streak heatmap, their assigned tasks, their projects' boards, EOD form, Timesheet."],
    ['Client', 'External users (e.g. an investor, a customer rep).', 'Read-only view of one project — milestones, status, deliverables. No internal tasks.'],
  ],
));
body.push(spacer());
body.push(h2('A day in the life'));
body.push(p('Here\'s how three different people use the platform on a typical Tuesday:'));
body.push(h3('Pankaj (founder, Super Admin)'));
body.push(p('He opens the laptop at 8:30 AM with a coffee. Goes straight to the Studio Portfolio. Scans the eight product cards in 5 seconds — RozCar has a red dot (something\'s wrong) and three blocked tasks. He clicks RozCar, sees the blockers, fires off a message to the lead. By 8:40 he\'s in the Triage Inbox, clearing the eight items that piled up overnight. Done with admin work by 9:00.'));
body.push(h3('Priya (engineer on Furix AI)'));
body.push(p('Opens her engineer dashboard at 9:30 AM. Sees her 12-day EOD streak (the fire icon next to her name is a tiny social-pressure thing). Opens "My Tasks", picks the highest-priority one, clicks it. Reads the description, ticks off two acceptance criteria as she works through the morning. At 6 PM she submits her EOD update — what she shipped, what blocked her, what she\'ll do tomorrow.'));
body.push(h3('Karthik (PM on RozCar)'));
body.push(p('Opens his PM dashboard at 10 AM after standup. Goes to the Sprints tab on RozCar. Realises Sprint 14 is winding down. Clicks Complete. The retro dialog opens — he fills in three things that went well, two that didn\'t, and one action item for next sprint. Picks which incomplete tasks should carry over. Hits "Complete sprint." Sprint closes, retro is saved forever.'));

// === Chapter 3: Login ===
body.push(h1('First Time Login'));
body.push(p('Before you can do anything else, you have to sign in. The login screen is the gateway — short, simple, no tricks.'));
body.push(...figure('01-login.png', 'The login screen, dark by default. Type your email, type your password, hit Enter.'));
body.push(h2('What you do'));
body.push(...numbered([
  "Open https://central.exargen.com/login in your browser.",
  "Type your email address. It will end in @exargen.in (or your client domain).",
  "Type your password. The default for new accounts is 'Admin@1234' — change it on first login.",
  "Press Enter or click Sign in.",
]));
body.push(h2('What happens next'));
body.push(p('The platform looks at your role and sends you to the right homepage:'));
body.push(...bullets([
  "If you're a Super Admin or Admin → /dashboard (the Studio Portfolio).",
  "If you're a Product Manager → /pm/dashboard.",
  "If you're an Engineer → /eng/dashboard.",
  "If you're a Client → /client/dashboard (most clients have only one project, so they auto-redirect to that project's status page).",
]));
body.push(h2('Why dark mode by default'));
body.push(p(
  'The platform is built around an "Obsidian" visual language — warm-dark backgrounds, a single violet accent colour, restraint everywhere else. Engineers spend ten hours a day looking at screens; dark mode is friendlier to their eyes. If you prefer light mode, click the sun/moon icon in the top right; the platform remembers your choice forever (per device).',
));
body.push(h2('What problem this solves'));
body.push(p(
  "Most workplace tools feel like office software from 2010 — bright white screens that fry your eyes, too many colours fighting for attention, fonts that are too small. Engineers in particular hate this. They want a tool that feels like Linear, VS Code, or Spotify — calm, focused, dark by default. Login is your first impression of the product, and we wanted that impression to say: 'this was built by people who care about the details.'",
));

// === Chapter 4: Studio Portfolio ===
body.push(h1('The Studio Portfolio (Admin Homepage)'));
body.push(p(
  "When the founder or an admin signs in, the first thing they see is the Studio Portfolio. This page exists to answer one question: 'where do I look first this morning?'",
));
body.push(...figure('02-studio-portfolio.png', 'The Studio Portfolio at /dashboard. Four bands stacked top to bottom — every product, every active task, every chart, every alert in one screen.'));
body.push(h2('What problem this solves'));
body.push(p(
  "The founder is busy. They have eight products, dozens of engineers, hundreds of tasks. Without a screen like this, every morning becomes a 30-minute scavenger hunt — open Linear, switch to Furix project, check status, go to Slack, ask 'how is RozCar doing', open Notion, find the roadmap, etc. With this screen, the same answer appears in 5 seconds.",
));
body.push(h2('The four bands'));
body.push(p('From top to bottom, the page is divided into four sections we call "bands". Each band exists to answer a specific question.'));
body.push(h3('Band 1 — Product Health Grid'));
body.push(p('A row of eight cards, one per product. Each card shows:'));
body.push(...bullets([
  "Product name and the project lead's initials in a circle (so you know who to tap).",
  "A health dot — green if everything is fine, amber if something needs watching, red if something is broken.",
  "The current sprint's progress as a thin segmented bar (each segment is one task, filled if done).",
  "How many tasks are blocked, in red.",
  "An 8-week velocity sparkline — a tiny chart showing how many tasks the team finished each week. Trend going up = healthy. Going down = trouble.",
]));
body.push(p('Hovering shows the current sprint goal in a tooltip. Clicking a card drops you into that product\'s Board.'));
body.push(...quote(
  "The Product Health Grid replaced my morning Slack ritual of asking eight different leads how their product was doing. Now I just look at the dots.",
  'Pankaj, founder',
));
body.push(h3('Band 2 — Cross-Product Sprint Stream'));
body.push(p(
  "A unified list of every active-sprint task across every product, grouped by status (In Progress, In Review, Up Next). Filter chips at the top let you slice the view: by product (click 'Furix AI 6' to see only Furix tasks), by priority (P0, P1), or 'Blocked'. Click again to remove the filter.",
));
body.push(p(
  "This is the closest thing to a 'live cross-product feed' the platform has. It tells you exactly what's being worked on right now, everywhere.",
));
body.push(h3('Band 3 — Capacity & Velocity'));
body.push(p('Three small charts side by side:'));
body.push(...bullets([
  "Capacity — how loaded each product is right now. Tall stacked bars = lots of work. Catches over-loaded products before they burn out.",
  "Velocity — eight weeks of completed-task counts per product, drawn as overlapping lines with a median reference. Spot which products are accelerating and which are slowing.",
  "My time this week — a small pie chart showing where you (the logged-in admin) personally spent your effort this week, broken down by product. Tells you if your attention matched your priorities.",
]));
body.push(h3('Band 4 — Attention List'));
body.push(p(
  "An automatically-generated list of items that need a routing decision today. The platform watches your data and surfaces:",
));
body.push(...bullets([
  "Tasks that have been blocked for more than three days.",
  "Tasks in active sprints that don't have an assignee yet.",
  "New bugs reported in the last 24 hours that don't have an owner.",
  "Engineers who didn't submit yesterday's End-of-Day update.",
  "Active-sprint tasks that don't have an Epic (a hygiene check).",
]));
body.push(p(
  "Each row has an action button (Unblock, Assign, Nudge, Triage). Clicking the count opens the full Triage Inbox.",
));
body.push(h2('Real-world example: Pankaj on a Wednesday morning'));
body.push(p(
  "He opens /dashboard at 8:30 AM. The RozCar card has a red health dot and shows '3 blocked'. The Attention List has 11 items, two of which are about RozCar. He clicks the count, lands on /inbox, and clears those eleven decisions in eight minutes. By 8:40 he's done with admin work and ready for deep focus.",
));
body.push(h2('How it compares to other tools'));
body.push(table(
  ['Tool', 'Their version', 'Our version'],
  [
    ['Linear', 'My Issues — your own work, vertically.', 'Studio-wide. Eight products at once.'],
    ['Jira', 'Portfolio plugin (paid add-on) shows roadmap timelines.', 'Built in. Not a roadmap; a live cockpit.'],
    ['Notion projects', 'A flexible database — you build the view yourself.', 'Opinionated four-band layout, ready to use.'],
  ],
));

// === Chapter 5: Triage Inbox ===
body.push(h1('The Triage Inbox (Morning Ritual)'));
body.push(p(
  "If the Studio Portfolio is the cockpit, the Triage Inbox is the doormat. It is the small pile of decisions that need to be made today before deep work starts. Clear it to zero every morning and the rest of your day is free for real focus.",
));
body.push(...figure('03-triage-inbox.png', 'The Triage Inbox at /inbox. Items grouped by kind, severity-sorted. A side rail on the right peeks at the task without you clicking.'));
body.push(h2('What problem this solves'));
body.push(p(
  "When you run multiple products, decisions pile up overnight. A bug got reported. Someone forgot to assign a task. A blocker has been sitting for too long. An engineer didn't submit their daily update. Each one is small, but together they steal an hour of your morning if you have to find them yourself across eight projects.",
));
body.push(p(
  "The Triage Inbox finds them for you. It runs queries against every project every minute and shows the things that need a routing decision. The goal is to clear the inbox to zero, every morning. When it's empty, you get a celebratory 'Triage clean ✓' screen — finishing the morning ritual feels like crossing the finish line of a workout.",
));
body.push(h2('The five kinds of items'));
body.push(table(
  ['Kind', 'What it is', 'Severity', 'Quick action'],
  [
    ['Blocked & aging', "A task that's been marked blocked for more than 3 days.", 'High', 'Unblock'],
    ['New bugs', "A bug reported in the last 24 hours with no assignee.", 'High', 'Triage'],
    ['Unassigned in sprint', "A task already in an active sprint with nobody assigned.", 'Medium', 'Assign'],
    ['No epic in sprint', "Active-sprint task without an Epic — a hygiene check.", 'Low', 'Set epic'],
    ['Missing EOD', "An engineer who didn't submit yesterday's End-of-Day update.", 'Low', 'Nudge'],
  ],
));
body.push(h2('Power features'));
body.push(...bullets([
  "Filter chips with live counts. Toggle a kind on/off; click 'Show all' to bring everything back.",
  "Press J or down-arrow to walk down the list. K or up-arrow to walk back up.",
  "Press Enter on a focused row to take its action (jump to the project or the task).",
  "Press Esc to drop focus.",
  "Hover any row that points to a task — the side rail on the right peeks the task title, description, status, priority, and assignee. Saves a click for fast scanning.",
  "When the inbox is empty, the page shows a 'Triage clean ✓' celebration with a glowing emerald ring and sparkles. Treat it like finishing a workout.",
]));
body.push(h2('Real-world example: Karthik finds and fixes a CVE in two days'));
body.push(p(
  "Day 1, 9:02 AM. Karthik opens /inbox. The first item — high severity — reads: 'Furix AI · JWT verifier path traversal · Blocked 4d.' He hovers; the side rail shows the task description. He hits Enter, lands on the task, reads the blocker note. A teammate had been waiting for him to confirm the scope. He confirms in a comment, unblocks the task, and starts work.",
));
body.push(p(
  "Day 1, 6:30 PM. The patch is in code review. He marks the original task done, opens a new sub-task for 'Write CVE advisory blog post', and links it to the original via a 'Relates to' link.",
));
body.push(p(
  "Day 2, 11 AM. The CVE blog post template (already defined in the CMS settings for Furix Marketing) gets filled in with CVSS 7.4, mitigation YAML, and the coordinated-disclosure timeline. By lunchtime CVE-2026-1872 is publicly disclosed and patched.",
));
body.push(p(
  "Without the inbox, that sequence would have started at least 24 hours later. The platform compressed two days of triage-and-decide into one morning.",
));

// === Chapter 6: Project Workspace ===
body.push(h1('Inside a Project'));
body.push(p(
  "When you click a product card from the Studio Portfolio (or the Projects tab in the sidebar), you arrive at that product's project workspace. Every product has the same eight tabs along the top.",
));
body.push(h2('The tabs explained'));
body.push(table(
  ['Tab', 'What lives here'],
  [
    ['Board', 'The visual sticky-note wall where day-to-day work happens. Five columns: Backlog, To Do, In Progress, In Review, Done.'],
    ['Sprints', 'Two-week chunks of work. Active sprint, planning sprints, completed sprints with retros.'],
    ['Epics', 'Big themes that group many tasks (e.g. "Knowledge Graph", "SIEM Collector"). Each epic has its own progress bar.'],
    ['Timeline', 'Roadmap-style horizontal view of milestones across time.'],
    ['Deliverables', 'Artifacts the client signs off on. Versioned, audited.'],
    ['Decisions', 'Log of architecture or product decisions made and why.'],
    ['Analytics', 'Velocity, blocker aging, status distribution charts for this product.'],
    ['Settings', 'Per-project Custom Fields editor (covered in its own chapter).'],
  ],
));

body.push(h2('Tab 1: The Board (kanban)'));
body.push(...figure('04-project-detail-board.png', 'A project Board with five columns. WIP limits in the column pills. Filter chips at the top. Aging dots on stale cards.'));
body.push(p(
  "The Board is the visual heart of every product. Five columns left to right: Backlog (someday work), To Do (planned but not started), In Progress (actively being worked on), In Review (waiting for a check), and Done.",
));
body.push(h3('Power features that make it fast'));
body.push(...bullets([
  "WIP limits — each column shows '3/8' meaning 3 of 8 allowed. Goes amber at the limit, red over it. Soft signal — doesn't block adds, just reminds the team.",
  "Aging dots — a small dot on the top-right of cards that have sat in the same column for too long. Yellow at 3 days, red at 5+. Catches forgotten work.",
  "Quick filter chips — My issues, Unassigned, P0, P1, Blocked. Click to toggle. They use real database counts, not the filtered view.",
  "Drag and drop — pick up a card, drop it in a different column, the status changes instantly. Optimistic update; it appears moved before the server confirms.",
  "Inline + button on each column to add a task without leaving the board.",
  "Keyboard navigation (the next chapter has the full list).",
]));
body.push(h3('Industry comparison'));
body.push(...bullets([
  "Linear's board is the gold standard for keyboard speed. Ours is patterned after it (J/K nav, ? for help).",
  "Jira's board is more familiar to most teams but feels heavier — every action takes 2-3 clicks.",
  "Notion's kanban is beautiful but slows down past 100 tasks.",
]));
body.push(p("Our Board sits at \"Linear speed with Jira's WIP-limit discipline\"."));

body.push(h2('Tab 2: Sprints'));
body.push(...figure('05-project-detail-sprints.png', 'The Sprints tab. Active sprint at the top with a burnup chart, scope-creep pill, completed/total points. Below: backlog and completed sprints.'));
body.push(p(
  "Sprints are two-week (typical) time-boxed chunks of work. The team commits to a list of tasks at the start; tracks progress through the burnup chart in the middle; ends the sprint with a structured retrospective.",
));
body.push(h3('What the active sprint card shows'));
body.push(...bullets([
  "The sprint goal — one sentence describing what success looks like. Editable in place (click the pencil).",
  "Date range, task and points totals.",
  "A scope-creep pill — 'Scope +6pt' shows up when tasks were added after the sprint started. Spot scope creep without digging.",
  "An inline burnup chart — completed-points filled-area + ideal-pacing dashed line + scope reference line. Built from real status-change history so reopened tasks don't bounce the chart.",
  "A 'Complete' button that opens the retro dialog.",
]));
body.push(h3('The retrospective dialog'));
body.push(p('When you press Complete, you do not get a simple "are you sure?" confirm. You get a real retrospective form:'));
body.push(...numbered([
  'What went well? — patterns to keep doing.',
  "What didn't? — friction worth surfacing.",
  "Action items — concrete commitments for next sprint.",
  "A checklist of incomplete tasks — pick which ones carry over.",
  "A 'Move to' selector — backlog OR another active/planning sprint.",
]));
body.push(p(
  "All of this is saved as part of the sprint forever. You can scroll back through old completed sprints and read what the team learned. Most teams have retros but the notes vanish; ours don't.",
));

body.push(h2('Tab 3: Epics'));
body.push(...figure('06-project-detail-epics.png', 'The Epics tab. A searchable list of large bodies of work, each with a color stripe, status badge, progress bar, and points done/total.'));
body.push(p(
  "An Epic is a layer above tasks. Each epic groups a coherent body of work that spans multiple sprints — for example, 'Knowledge Graph' might be 50 tasks across 4 sprints. Epics let you point at a single thing and see how the whole stream is progressing.",
));
body.push(h3('Each epic row shows'));
body.push(...bullets([
  "A color stripe on the left (8-color curated palette).",
  "A status badge — Open, In Progress, or Done.",
  "A live progress bar that updates automatically as tasks complete.",
  "Points done out of total (e.g. 13/34).",
  "Hover to reveal edit and delete buttons. Deleting an epic unassigns its tasks rather than deleting them — safer.",
]));
body.push(p('Click any epic row → a slide-over panel opens on the right with the epic\'s description, full progress rollup, and every task grouped by status.'));

body.push(h2('Tab 4: Settings — Custom Fields per product'));
body.push(...figure('07-project-detail-settings.png', "Project Settings. Per-product custom fields. Each row shows the field's label, type, key, and required flag."));
body.push(h3('What problem this solves'));
body.push(p(
  "Different products need to track different structured data. Furix AI tracks CVE IDs and CVSS scores. RozCar tracks KYC status (pending, verified, failed). ManaCalendar tracks Tithi names. Off-the-shelf tools like Linear or Trello make you cram all this into 'labels' or 'description text', which gets lost in a search.",
));
body.push(p(
  "Our Custom Fields system lets each product define its own typed fields, with proper inputs, validation, and rendering. The Settings tab is where admins or PMs define those fields. The fields then appear on every task in that project.",
));
body.push(h3('Six field types'));
body.push(table(
  ['Type', 'What it stores', 'Real example'],
  [
    ['TEXT', 'Free-form text. Optional max length and multiline.', 'Furix: CVE ID = "CVE-2026-1872"'],
    ['NUMBER', 'A number, with optional min/max/step.', 'Furix: CVSS Score = 7.4 (range 0–10)'],
    ['SELECT', 'Pick one (or many) from a fixed list. Options can be colored.', 'RozCar: KYC Status = pending / verified / failed / expired'],
    ['DATE', 'Calendar date.', 'A regulatory-deadline tracker for compliance work.'],
    ['URL', 'External link. Renders with an open-in-new-tab icon.', 'A link to the affected docs page.'],
    ['BADGE', 'Yes/no flag rendered as a coloured chip.', '"Featured" or "Customer-reported".'],
  ],
));
body.push(h3('Safety rails'));
body.push(...bullets([
  "Required fields are enforced server-side. If you mark CVE ID as required, every Furix task must have one.",
  "Type changes are blocked once values exist — turning a TEXT into a SELECT would silently lose data.",
  "Deleting a field also scrubs that key from every task in a single transaction. No orphan data.",
  "Hard caps: 30 fields per project, 50 SELECT options, lowercase-snake-case keys ≤40 characters.",
]));
body.push(h3('How to use'));
body.push(...numbered([
  "Open the project. Click the Settings tab.",
  "Click 'New field'.",
  "Type a name (e.g. 'CVE ID'). The key auto-fills (cve_id).",
  "Pick a type from the dropdown. Type-specific config appears below.",
  "Optionally tick 'Required' if every task in this project must fill this in.",
  "Save. Open any task in this project — your new field appears in the 'Custom Fields' section.",
]));

// === Chapter 7: Task Detail ===
body.push(h1('The Task — Where Real Work Happens'));
body.push(...figure('08-task-detail.png', 'The Task Detail page. Title at the top, copy-link button. Status / Priority / Assignee / Sprint / Epic. Custom Fields. Acceptance Criteria. Subtasks. Linked Issues. Comments.'));
body.push(p(
  "If the Board is the wall of sticky notes, a Task is a single sticky note expanded into all its glory. This is where engineers actually do the work — read the description, update the status, tick off acceptance criteria, link to other tasks, leave comments.",
));
body.push(h2('Two ways to open a task'));
body.push(...bullets([
  "From the Board: click any card. A slide-over panel appears on the right. Press J/K to walk through siblings without closing.",
  "Direct link: /projects/<projectId>/tasks/<taskId> — bookmarkable, share-able. Same content, more breathing room.",
]));
body.push(p('There is a Maximize button in the slide-over header that switches you from the slide-over to the full page if you want more room.'));

body.push(h2('Sections of a task, top to bottom'));
body.push(h3('Header'));
body.push(p('Title (click to edit), status pill, copy-link button, expand-to-full-page button, delete button (admins only).'));
body.push(h3('Status, Priority, Assignee, Due date, Story points, Sprint, Epic'));
body.push(p('Standard fields. All editable in place. Story points are the team\'s estimate of effort (Fibonacci: 1, 2, 3, 5, 8, 13). Priority is P0 (critical) through P3 (low).'));
body.push(h3('Description'));
body.push(p('Free-form text. Auto-saves on blur (when you click outside the box).'));
body.push(h3('Acceptance Criteria — the Done-gate'));
body.push(p(
  "A checklist. Each line is one thing that must be true before the task can be marked Done. The platform server actually blocks a status change to Done if any acceptance criterion is unchecked, with a clear inline error.",
));
body.push(...quote(
  "Acceptance Criteria are not decorative. The server says no.",
  'Build philosophy',
));
body.push(p('This is the single most underrated feature for engineering teams. Most tools let you check Done with no AC; ours forces you to make AC real.'));
body.push(h3('Subtasks'));
body.push(p('A nested checklist below the main task — for technical steps that aren\'t worth their own task. Add (Enter), edit (double-click), toggle, delete. Server caps at 50 items.'));
body.push(h3('Custom Fields'));
body.push(p('Whatever the project Settings tab defines. For Furix tasks: CVE ID, CVSS Score, Affected Component dropdown. Auto-saves on blur. Validation errors appear inline next to the offending field.'));
body.push(h3('Linked Issues'));
body.push(p('Five buckets of relationships:'));
body.push(...bullets([
  'Blocks — this task blocks another from progressing.',
  'Blocked by — this task is waiting on another.',
  'Related to — peer relationship; loosely connected.',
  'Duplicates — this task is a copy of another.',
  'Duplicated by — another task is a copy of this one.',
]));
body.push(p(
  "Cycle detection: the server refuses to create A → B if a path B → ... → A already exists. Catches both direct cycles (A blocks B; B blocks A) and transitive cycles (A blocks B; B blocks C; C blocks A). Bounded BFS so an adversarial graph can't burn the server.",
));
body.push(h3('Comments'));
body.push(p('Markdown comments with one-level threading. @-mentions notify other users.'));
body.push(h3('Activity / Timestamps'));
body.push(p('Created/Updated relative timestamps + a hint at the bottom showing the J/K keyboard hint when in the slide-over.'));

body.push(h2('Real-world example: shipping the Furix CVE patch'));
body.push(p('Karthik creates a task on Furix titled "JWT verifier bypass — patch ≤v8.4". He fills in:'));
body.push(...bullets([
  'Description: a few paragraphs of context with reproduction steps.',
  'Custom Fields: CVE ID = "CVE-2026-1872", CVSS Score = 7.4, Affected Component = "auth".',
  'Acceptance Criteria: (1) Patch lands in v8.5.0; (2) All staging tenants upgrade; (3) Public advisory drafted.',
  'Linked Issues: blocks "Furix Voice 2.0 launch" (the launch must wait until the security patch ships).',
  'Priority: P0.',
  'Sprint: assigned to the active sprint.',
]));
body.push(p(
  "Day 1: he ticks AC #1 as soon as the patch lands. Tries to mark Done — server refuses, two AC still unchecked. Day 2: AC #2 done. Day 2 evening: AC #3 done. Now Done works. The task closes; the linked 'Voice 2.0 launch' is automatically unblocked.",
));

// === Chapter 8: Keyboard Shortcuts ===
body.push(h1('Keyboard Shortcuts (For People Who Love Speed)'));
body.push(p(
  "The platform is keyboard-driven. Power users can drive 90% of common actions without touching the mouse. Press ? anywhere on the Board to bring up the cheat sheet.",
));
body.push(...figure('09-keyboard-shortcuts.png', 'The keyboard shortcuts modal. Three sections: Board navigation, focused-card actions, and slide-over navigation.'));
body.push(h2('Board navigation'));
body.push(table(
  ['Key', 'What it does'],
  [
    ['C', 'Quick-add a task (in the focused column).'],
    ['J / K / ↓ / ↑', 'Move focus between cards.'],
    ['← / →', 'Move focus between columns.'],
    ['Enter', 'Open the focused task in the slide-over.'],
    ['Esc', 'Clear focus or close panels (cascading).'],
    ['?', 'Show / hide this help.'],
  ],
));
body.push(h2('On the focused card'));
body.push(table(
  ['Key', 'What it does'],
  [
    ['1', 'Set priority to P0 (Critical).'],
    ['2', 'Set priority to P1 (High).'],
    ['3', 'Set priority to P2 (Medium).'],
    ['4', 'Set priority to P3 (Low).'],
  ],
));
body.push(h2('In the slide-over (open task)'));
body.push(table(
  ['Key', 'What it does'],
  [
    ['J', 'Next sibling task in the visible list.'],
    ['K', 'Previous sibling task.'],
    ['Esc', 'Close the slide-over.'],
  ],
));
body.push(h2('Why these defaults'));
body.push(p(
  "We modelled them on Linear and Vim. J/K for next/prev because every developer who has ever used Vim has those keys in muscle memory. ? for help because GitHub, Slack, and Linear all use ? for help — we didn't want to invent a new convention.",
));
body.push(p(
  "Crucially: shortcuts are always skipped while you're typing in an input or textarea. Pressing C while writing a comment doesn't yank you to a quick-add modal. Modifier keys (Cmd/Ctrl/Alt) also skip the shortcut. The platform never fights your keyboard.",
));

// === Chapter 9: Module Ratings ===
body.push(h1('Module Ratings — How Tight Is Each Piece?'));
body.push(p(
  "An honest self-assessment. Each module is rated 1 (early days) to 5 (industry parity or better). The studio average sits at about 4.5 out of 5 — a production-ready core with named follow-ups queued.",
));
body.push(table(
  ['Module', 'Rating', 'Why'],
  [
    ['Studio Portfolio', '5/5', 'Four bands, real data, scales to 8+ products without lag.'],
    ['Kanban Board', '5/5', 'Drag, keyboard, WIP limits, aging dots, filters, slide-over. Linear-class speed.'],
    ['Sprint UX', '5/5', 'Editable goal, retro form with carry-over picker, inline burnup, scope-creep pill.'],
    ['Task Detail', '5/5', 'AC + Done-gate, sub-tasks, linked issues, copy link, J/K nav, custom fields. Industry parity.'],
    ['Linked Issues', '5/5', 'Cycle detection (direct + transitive), normalised symmetric links, in-project search picker.'],
    ['Custom Fields', '5/5', '6 field types, server validation, type-change guard, auto-scrub on delete, full settings UI.'],
    ['Theme', '5/5', 'Dark-by-default Obsidian palette, light mode preserved per user.'],
    ['Triage Inbox', '4/5', '5 alert kinds, J/K nav, hover preview, celebratory empty state. Future: inline mutations.'],
    ['Epics', '4/5', 'List, color, progress, slide-over. Future: per-epic burnup chart, group-by-epic on board.'],
    ['EOD Updates', '4/5', 'Auto-detect touched tasks, mood selector, streak heatmap. Future: Slack reminder integration.'],
    ['Analytics', '4/5', 'Velocity, blockers, distribution, attention. Future: per-engineer cycle time.'],
    ['Activity Feed', '4/5', 'Every mutation logged transactionally. Future: filter by user/date range.'],
    ['Auth + RBAC', '4/5', 'Per-permission UI, role-aware nav, project-membership gates. Future: SSO + 2FA.'],
    ['CMS (content)', '3/5', 'Project + blog + template models, public API key. Now seeded with realistic content. Future: rich-text polish, media library.'],
  ],
));
body.push(p('Studio average: ~4.5 out of 5. Production-ready core, with two named follow-ups queued: D-2 (multi-select bulk operations on the Board) and G (Roadmap view with draggable Epic bars).'));

// === Chapter 10: Getting started ===
body.push(h1('How to Get Started Today'));
body.push(p(
  "Whoever you are, here's a 5-step plan for your first week. Follow it and you'll have the platform doing real work for you by Friday.",
));
body.push(h2('If you are a Super Admin / Admin'));
body.push(...numbered([
  'Day 1, morning: sign in. Spend 5 minutes scrolling the Studio Portfolio. Get a feel for the four bands.',
  'Day 1, afternoon: open /inbox. Clear today\'s items. Notice how it feels to finish.',
  "Day 2: pick the product you're most worried about. Click its card. Switch to Sprints tab. Read its current sprint goal. Check the burnup.",
  "Day 3: open Settings on one project. Define a custom field that's specific to that product (e.g. CVE ID for Furix). Open a task. See the new field render.",
  'Day 4-5: build the habit — clear /inbox every morning, look at /dashboard post-lunch, review the completed-sprint retros every Friday.',
]));
body.push(h2('If you are a Product Manager (PM)'));
body.push(...numbered([
  'Day 1: sign in to /pm/dashboard. See your portfolio.',
  "Day 2: open one of your projects. Spend time on Epics — define the strategic threads (e.g. for RozCar: 'KYC Verification', 'Booking Flow', 'Driver Onboarding').",
  'Day 3: assign tasks to epics. Watch the epic progress bars start to move.',
  "Day 4: hit ? on the Board. Memorise C and J/K. They'll save you minutes per day.",
  'Day 5 / End of sprint: open the active sprint. Click Complete. Run the retro form properly — three entries in each section, even if one of them is just "team morale was high". The next-sprint discussion will benefit from it.',
]));
body.push(h2('If you are an Engineer'));
body.push(...numbered([
  'Day 1: sign in to /eng/dashboard. See your streak heatmap (probably empty on day 1).',
  'Day 2: open /eng/my-tasks. Pick the highest-priority task. Click it. Open the slide-over.',
  "Day 3: practice the keyboard shortcuts. C to add a sub-task. J/K to walk between tasks.",
  'Day 4: at 6 PM, submit your EOD update. The platform auto-suggests the tasks you touched today; you just write a one-line "what progress?" for each.',
  'Day 5: build the streak. The fire icon next to your name is social pressure masquerading as a graphic. After 5 days you\'ll feel weird about breaking it.',
]));
body.push(h2('If you are a Client'));
body.push(...numbered([
  'Sign in. Single-project clients auto-redirect to your project status page.',
  'Read the milestones, current status, and any deliverables waiting for sign-off.',
  'Sign off completed deliverables (a button on each artifact).',
  "Comment on items you have questions about — comments are visible to the project's PM and engineers.",
  "If you need access to more projects, contact your Exargen account manager.",
]));

// === Chapter 11: Real-world stories ===
body.push(h1('Real-World Stories'));
body.push(p(
  "Three concrete scenarios that show the platform in action. Made up but based on the kind of day-to-day work the studio actually does.",
));

body.push(h2('Story 1 — A bug becomes a CVE in 48 hours'));
body.push(p(
  "Wednesday 11 AM. A Furix customer reports an authentication oddity over Slack. Pankaj forwards it to Karthik. Karthik creates a task on Furix in 30 seconds (presses C from the Board, types the title, hits Enter). He marks it P0 because the customer's tone was urgent.",
));
body.push(p(
  "By 4 PM Karthik has reproduced the issue. He fills in the Custom Fields: CVE-2026-1872, CVSS 7.4, Affected Component = auth. He defines three Acceptance Criteria. He links the task to the upcoming 'Furix Voice 2.0' launch task with a 'blocks' link — the launch can't ship until this is patched.",
));
body.push(p(
  "Thursday 2 PM. The patch lands in v8.5.0-rc1. AC #1 ticks. AC #2: staging upgrade in progress. AC #3: advisory drafted in the CMS using the 'Security Advisory' template (already defined for Furix Marketing). By 6 PM all three AC tick green; Karthik tries to move the task to Done. Server allows it. The 'blocks' link automatically clears; the Voice 2.0 launch task is no longer blocked.",
));
body.push(p(
  "Friday 8 AM. Public disclosure. The advisory blog post (already drafted in the CMS) is published. CVE-2026-1872 closes. Total elapsed: 45 hours. Without the platform: probably 4-5 days.",
));

body.push(h2('Story 2 — Sprint retro reveals a process bug'));
body.push(p(
  "End of Sprint 14 on RozCar. The team built six features, finished four. The other two need to carry over. Karthik opens the active sprint card and presses Complete.",
));
body.push(p('The retro dialog opens. He fills in:'));
body.push(...bullets([
  'What went well: "KYC integration with Surepass shipped a week early. Pairing on the booking-conflict bug worked."',
  'What didn\'t: "Our standup drifted from 9:30 to 11 AM by Thursday — we lost context. The notification system is too verbose; engineers tune them out."',
  'Action items: "Move standup back to 9:30 IST. Add notification-volume preferences in Q3."',
]));
body.push(p(
  "He picks the two incomplete tasks to carry over to Sprint 15 (the planning sprint). Hits Complete. Sprint 14 closes; the retro is saved as part of the sprint forever. Three sprints later when the team is wondering 'why did we move standup back to 9:30?', they open Sprint 14, scroll to retro, and see the answer. No memory loss, no Slack-archaeology.",
));

body.push(h2('Story 3 — Pankaj does a Friday review in 12 minutes'));
body.push(p(
  "Friday 4:30 PM. Pankaj opens /dashboard. He spends 60 seconds on each band:",
));
body.push(...bullets([
  "Band 1 (Product Health): scans the 8 cards. ManaCalendar's velocity sparkline is dropping — flag for next week.",
  "Band 2 (Sprint Stream): filters by 'Blocked'. Two items blocked across all 8 products. Both are RozCar; both are waiting on the same external dependency. He sends one Slack message asking the dependency owner for an ETA.",
  "Band 3 (Capacity): RozCar's capacity bar is the largest. The team is over-loaded. He notes it for sprint planning Monday.",
  "Band 4 (Attention): six items. Three are blocked-aging (one per product). Two are missing-EOD. One is unassigned in active sprint. He clicks the count, lands on /inbox, clears all six in 7 minutes.",
]));
body.push(p(
  "Total time: 12 minutes. He has a clear-eyed read on the studio for the weekend, has nudged the things that needed nudging, and has empty headspace until Monday standup. Without the platform, this same review would have taken him 90 minutes of digging across Linear, Slack, and Notion.",
));

// === Chapter 12: Glossary ===
body.push(h1('Glossary — Plain-English Definitions'));
body.push(table(
  ['Term', 'What it means here'],
  [
    ['Studio', 'The whole company. All eight products live in one Exargen instance.'],
    ['Product / Project', 'A single product (Furix AI, RozCar, etc.). One project = one workspace.'],
    ['Epic', "A coherent body of work spanning 2-8 sprints. Example: Furix's 'Knowledge Graph'."],
    ['Sprint', "A time-boxed chunk of work, typically two weeks. The team commits at the start and reviews at the end."],
    ['Task', "A single unit of work. Has status, priority, assignee, story points, etc."],
    ['Acceptance Criteria (AC)', "Given/When/Then statements that must all be ticked ✓ before a task can be Done. Server-enforced."],
    ['Linked Issue', "A relationship between two tasks: blocks / blocked-by / relates / duplicates."],
    ['Custom Field', "A per-project structured field defined in Settings (CVE, KYC, Tithi …)."],
    ['EOD', "End-of-Day update. Submitted once per workday by each engineer."],
    ['WIP limit', "Soft cap on how many tasks should sit in In Progress / In Review at once."],
    ['Aging dot', "Visual signal that a card has been sitting in the same column for more than 3 days."],
    ['Triage', "Routing decisions made on new / blocked / orphan items."],
    ['Burnup', "Chart showing completed-points climbing toward the sprint's total scope. Better than burndown for visualising progress."],
    ['Scope creep', "Tasks added to a sprint after it started."],
    ['RBAC', "Role-Based Access Control. The system that decides who can do what."],
    ['Optimistic UI', "When a click appears to take effect immediately, before the server confirms it. If the server rejects, the UI rolls back."],
  ],
));

// === Chapter 13: Where this lives ===
body.push(h1('Where This Document Lives'));
body.push(p('This is the canonical product guide. It exists in two formats:'));
body.push(...bullets([
  "docs/PRODUCT_GUIDE.md — the Markdown version. GitHub renders it inline with screenshots in any pull request.",
  "docs/PRODUCT_GUIDE.docx — this Word version. Built from the same source content, suitable for sharing with non-technical stakeholders, printing, or reading offline.",
]));
body.push(p(
  "Both files are kept in version control. When a feature changes, the guide is updated in the same pull request. Anyone can update it; you don't need approval to fix a typo.",
));
body.push(h2('How to refresh the screenshots'));
body.push(p('From the repo root:'));
body.push(...bullets([
  'npx tsx scripts/capture-screenshots.ts — runs Playwright against the local dev servers, walks every major surface, saves PNGs into docs/screenshots/.',
]));
body.push(p('It logs in as admin@exargen.in / Admin@1234 against http://localhost:5174 (frontend) + http://localhost:3002 (backend). Re-run any time the UI changes.'));
body.push(h2('How to rebuild this Word document'));
body.push(p('From the repo root:'));
body.push(...bullets([
  'npx tsx scripts/build-product-guide-docx.ts — reads docs/screenshots/ and outputs docs/PRODUCT_GUIDE.docx.',
]));
body.push(h2('Final note'));
body.push(p(
  "This platform was built in roughly two weeks of focused work — eight pull requests merged into main plus a quality-fix patch and three demo-data seed scripts. It is not a beta or a prototype; it is the studio's daily driver.",
));
body.push(p(
  "If you find anything in this document that is wrong, stale, or unclear, fix it in a small pull request. The doc is the single source of truth, and stale docs are worse than no docs.",
));
body.push(p(' '));
body.push(p(' '));
body.push(p('— End of guide —', { italic: true }));

// ─── Build the document ───────────────────────────────────────────────────────

const doc = new Document({
  creator: 'Exargen Studio',
  title: 'Exargen Command Center — Product Guide',
  description: 'Single source of truth covering every feature of the platform.',
  styles: {
    default: { document: { run: { font: FONT, size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 36, bold: true, font: FONT, color: TITLE_COLOR },
        paragraph: { spacing: { before: 360, after: 240 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 28, bold: true, font: FONT, color: TITLE_COLOR },
        paragraph: { spacing: { before: 240, after: 160 }, outlineLevel: 1 } },
      { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true,
        run: { size: 24, bold: true, font: FONT, color: TITLE_COLOR },
        paragraph: { spacing: { before: 200, after: 120 }, outlineLevel: 2 } },
    ],
  },
  numbering: {
    config: [
      { reference: 'bullets',
        levels: [{ level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      { reference: 'numbers',
        levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
    ],
  },
  sections: [
    // ─── Cover page ─────────────────────────────────────────────────────────
    {
      properties: {
        page: {
          size: { width: 12240, height: 15840 }, // US Letter
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children: coverPage,
    },
    // ─── Main body with TOC + chapters ──────────────────────────────────────
    {
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      headers: {
        default: new Header({
          children: [new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [new TextRun({
              text: 'Exargen Command Center — Product Guide',
              font: FONT, size: 18, color: SUBTLE_COLOR, italics: true,
            })],
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({ text: 'Page ', font: FONT, size: 18, color: SUBTLE_COLOR }),
              new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 18, color: SUBTLE_COLOR }),
              new TextRun({ text: ' of ', font: FONT, size: 18, color: SUBTLE_COLOR }),
              new TextRun({ children: [PageNumber.TOTAL_PAGES], font: FONT, size: 18, color: SUBTLE_COLOR }),
            ],
          })],
        }),
      },
      children: [
        // TOC heading + auto-TOC field. Word will populate this on open.
        new Paragraph({
          heading: HeadingLevel.TITLE,
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: 'Table of Contents', font: FONT, bold: true, size: 36, color: TITLE_COLOR })],
        }),
        spacer(),
        new TableOfContents('Table of Contents', { hyperlink: true, headingStyleRange: '1-3' }),
        // Body content (each h1 has pageBreakBefore so the TOC is its own page).
        ...body,
      ],
    },
  ],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, buffer);
  console.log(`✅ ${OUTPUT}`);
  console.log(`   Size: ${(buffer.length / 1024).toFixed(1)} KB`);
  console.log(`   Figures embedded: ${figureCounter}`);
});
